## Bhakti Javiya
## 216270307098

In [1]:
'''Write a NumPy program to implement following operation
 to convert a list of numeric values into a one-dimensional NumPy
array
'''

import numpy as np

list12 = [1, 2, 3, 4, 5]
arr = np.array(list12)
print(arr)

[1 2 3 4 5]


In [2]:
''' to create a 3x3 matrix with values ranging from 2 to 10'''

import numpy as np

val = np.arange(1, 28)

mat = val.reshape(3, 9)

print(mat)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


In [3]:
''' to append values at the end of an array'''

import numpy as np

arr = np.array([1, 2, 3])

print("ARRAY: ",arr)

arr2 = np.array([4, 5, 6])


appended = np.append(arr2, arr)

print("appended list: ",appended)

ARRAY:  [1 2 3]
appended list:  [4 5 6 1 2 3]


In [4]:
''' to create another shape from an array without changing its data(3*2
to 2*3) '''

import numpy as np
original = np.array([[10, 20],
                     [30, 40],
                     [50, 60]])


reshaped = original.reshape(2, 3)

print("Original Array:")
print(original)

print("Reshaped Array:")
print(reshaped)

Original Array:
[[10 20]
 [30 40]
 [50 60]]
Reshaped Array:
[[10 20 30]
 [40 50 60]]
